# Generated by Django 5.0 on 2023-12-07 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.TextField(verbose_name='First name')),
                ('last_name', models.TextField(verbose_name='Last name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone_number', models.TextField(verbose_name='Phone Number')),
                ('is_admin', models.BooleanField(verbose_name=False)),
            ],
        ),
    ]
