# Generated by Django 5.0 on 2023-12-07 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_admin',
            field=models.BooleanField(verbose_name='Admin Account'),
        ),
    ]
